version: '3.5'

volumes:
  postgres_data:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    restart: always
    environment:
      - SECRET_KEY_BASE=xxx
      - GOOGLE_API_KEY=xxx
      - GOOGLE_SHEET_ID=xxx
      - SLACK_WEBHOOK_URL=xxx
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
