version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          SECRET_KEY_BASE: my-circle-ci-secret-key
          GOOGLE_API_KEY: xx
          GOOGLE_SHEET_ID: xx
          SLACK_WEBHOOK_URL: xx
          DB_HOST: 127.0.0.1

      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sipanddip_test

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          keys:
            - sipanddip-api-bundle-v2-{{ checksum "Gemfile.lock" }}
            - sipanddip-api-bundle-v2-
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: sipanddip-api-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -f docker/app/Dockerfile -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG
      - store_test_results:
          path: test_results
