defaults: &defaults
  adapter: postgresql
  encoding: utf8
  min_messages: WARNING
  host: <%= ENV.fetch("DB_HOST") { localhost } %>
  username: postgres
  port: 5432
  pool: 10

development:
  <<: *defaults
  database: sipanddip_development

production:
  <<: *defaults
  database: sipanddip_production

staging:
  <<: *defaults
  database: sipanddip_staging

test:
  <<: *defaults
  database: sipanddip_test
