defaults: &defaults
  adapter: postgresql
  encoding: utf8
  min_messages: WARNING
  host: localhost
  database: sipanddip_development
  username:
  password:
  port: 5432
  pool: 10

development:
  <<: *defaults

production:
  <<: *defaults
  database: sipanddip_production

staging:
  <<: *defaults

test:
  <<: *defaults
  database: sipanddip_test
