development:
  secret_key_base: 9db21e076720993ffa3f489aaeb7c376daf1780b83a335512a053dc7ba7900d6336531e55b2062c038ca8cc97268d3d0c611bdff8dbf06f64262f66015a38055
  :google:
    :api_key: <%= ENV["GOOGLE_API_KEY"] %>
    :sheet_id: <%= ENV["GOOGLE_SHEET_ID"] %>
  :slack:
    :webhook_url: <%= ENV["SLACK_WEBHOOK_URL"] %>

test:
  secret_key_base: ea3394e26b2e0aae4b55b28da95e1eb66ed09d17e56f0b69feef822c2ba18178b1140d1db127e1245e2cbacc06f6b1f562ad8615ef36863e4244142d4473c3f3

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  :google:
    :api_key: <%= ENV["GOOGLE_API_KEY"] %>
    :sheet_id: <%= ENV["GOOGLE_SHEET_ID"] %>
  :slack:
    :webhook_url: <%= ENV["SLACK_WEBHOOK_URL"] %>
